services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./newsreader:/app/newsreader
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=pass
    command: ["poetry", "run", "uvicorn", "newsreader.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    networks:
      - backend

networks:
  backend: