services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env # only API_KEY here
    volumes:
      - ./newsreader:/app/newsreader
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=pass
      # API_KEY should be added here from .env automatically
    command: ["poetry", "run", "uvicorn", "newsreader.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db
    networks:
      - backend
    restart: always

  db:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  backend: